const express = require("express");
const bodyParser = require("body-parser");
require("dotenv").config();
const app = express();
const user = require("./routes/user");
const store = require("./routes/store");
const cart = require("./routes/cart");
const order = require("./routes/order");
const orderAdmin = require("./routes/orderAdmin");
const adminProduct = require("./routes/adminProduct");
const path = require("path");
const StartMongo = require("./config/db");
const cors = require("cors");
StartMongo();
const PORT = process.env.PORT || 5000;
app.use(cors({ credentials: true, origin: "*" }));
app.use(bodyParser.json());
app.use("/user", user);
app.use("/store", store);
app.use("/cart", cart);
app.use("/order", order);
app.use("/adminorder", orderAdmin);
app.use("/adminproduct", adminProduct);
app.use(express.static(path.join(__dirname, "frontend/build")));
app.get("*", (request, res) => {
  res.sendFile(path.join(__dirname + "/frontend/build/index.html"));
});
app.listen(PORT, () => {
  console.log(`Server started at PORT ${PORT}`);
});
